[build]
  command = "pnpm build"
  publish = "dist"
  base = "yttoolbox"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[dev]
  command = "pnpm dev"
  port = 5173
  targetPort = 5173
